"""Add relationships

Revision ID: 282dfbdadfb9
Revises: 90b781d954b6
Create Date: 2025-10-30 19:46:06.883603

"""

from alembic import op  # type: ignore
import sqlalchemy as sa  # type: ignore


# revision identifiers, used by Alembic.
revision = "282dfbdadfb9"
down_revision = "90b781d954b6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("book_copies", schema=None) as batch_op:
        batch_op.add_column(sa.Column("book_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "books", ["book_id"], ["id"])

    with op.batch_alter_table("checkouts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column("book_copy_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, "book_copies", ["book_copy_id"], ["id"])
        batch_op.create_foreign_key(None, "users", ["user_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("checkouts", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("book_copy_id")
        batch_op.drop_column("user_id")

    with op.batch_alter_table("book_copies", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("book_id")

    # ### end Alembic commands ###
